### ISSUE TITLE
Pluralized strings seem broken

### ISSUE THREAD

**Issue by ZRunner** [danhper/python-i18n#18]
According to #8, you can set pluralized strings in yaml files easily, without having to add them with a function like in the doc.

So I tested with the following `en.yml` file:
```yml
en:
  hi: Hello world !
  test:
    zero: "No follower"
    one: "1 follower"
    other: "%{count} followers"
```
And then the following Python code:
```py
import i18n

# configuring i18n [...]

print(i18n.t('hi'))
print(i18n.t('test', count=0))
```
The "hello world !" is correctly displayed, but the "No follower" isn't translated, thus only printing "test".
Having a `print(i18n.t('test.zero'))` however fixes the issue, but it's not really the expected way to do it lol.

**Package version:** 0.3.7
**Python version:** 3.8.5
